### ISSUE TITLE
ifs XML kaputt

### ISSUE THREAD

**Issue by thedm** [ktt-ol/website#46]
Derzeit ist im Atom-Feed ein Fehler, das Bild 560.jpg ist im [Atomfeed](https://www.kreativitaet-trifft-technik.de/media/ifs-images/feed.xml) vorhanden, aber das Bild ist nicht verfügbar und auf der normalen Webseite kommt man auch nicht auf das Bild.

**Comment by sre** [comment]
@smilix Das Bild hab ich gestern oder vorgestern akzeptiert und es ist per Deeplink auch verfügbar (https://www.kreativitaet-trifft-technik.de/media/ifs-images//0560.jpg). Es fehlt allerdings im meta.json, deshalb taucht es auf der Webseite nicht auf.

**Comment by smilix** [comment]
Das Script verschluckt sich an dem Bild:
```
Error: exif: tag "Model" is not present
```
Gucke ich mir morgen mal an.

**Comment by smilix** [comment]
Gefixt. ( https://github.com/ktt-ol/mfGalleryMetaCreatorGo/commit/b9d0e02b4560f6db79894cc57769cfd5ae891c31 )
